spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.CustomSerializer
      value-serializer: org.apache.kafka.common.serialization.CustomSerializer