spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${SECRET_KEY}
    token:
      access-expire-time: 86400 # 만료시간 하루
      refresh-expire-time: 2592000 # 만료시간 한 달

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  redis:
    host: j9a505.p.ssafy.io  # 레디스 호스트
    port: 6382  # 레디스 포트 (Redis Sentinel 포트로 설정)
    database: 1
    sentinel:
      master: mymaster  # Redis Sentinel의 마스터 이름
      nodes: j9a505.p.ssafy.io:26382, j9a505.p.ssafy.io:26383, j9a505.p.ssafy.io:26384  # Redis Sentinel 노드 목록


logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

server:
  port: 8081