spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}/auth
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jwt:
    secret: ${SECRET_KEY}
    token:
      access-expire-time: 86400 # 만료시간 하루
      refresh-expire-time: 2592000 # 만료시간 한 달

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    database: 1
    sentinel:
      master: ${REDIS_MASTER}
      nodes: ${REDIS_HOST}:26382, ${REDIS_HOST}:26383, ${REDIS_HOST}:26384
    lettuce:
      shutdown-timeout: 200ms


logging:
  level:
    org.hibernate:
      SQL: debug
      type: trace

server:
  port: 8081
