// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn6ygqXTyKLNU4dKiWN8QKXvy92-a_SJw',
    appId: '1:1076853604243:web:efc5beb3631c96380e3266',
    messagingSenderId: '1076853604243',
    projectId: 'a5052-59303',
    authDomain: 'a5052-59303.firebaseapp.com',
    storageBucket: 'a5052-59303.appspot.com',
    measurementId: 'G-Z0V172CR75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWUolE3oMp5hshCHWv_fob15zrnLmMuUE',
    appId: '1:1076853604243:android:76a85f323ea614160e3266',
    messagingSenderId: '1076853604243',
    projectId: 'a5052-59303',
    storageBucket: 'a5052-59303.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY-Nb9wQPc09vyJmsGRPquXLL4VWZ-m-c',
    appId: '1:1076853604243:ios:b23008253222f4760e3266',
    messagingSenderId: '1076853604243',
    projectId: 'a5052-59303',
    storageBucket: 'a5052-59303.appspot.com',
    iosBundleId: 'com.ssafy.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY-Nb9wQPc09vyJmsGRPquXLL4VWZ-m-c',
    appId: '1:1076853604243:ios:a1815446c6d6ce1d0e3266',
    messagingSenderId: '1076853604243',
    projectId: 'a5052-59303',
    storageBucket: 'a5052-59303.appspot.com',
    iosBundleId: 'com.ssafy.frontend.RunnerTests',
  );
}
